#ifndef PRINT_SOLUTION_H_INCLUDED
#define PRINT_SOLUTION_H_INCLUDED

enum RETURN_CODES_FOR_PRINT {
    SUCCESSFUL_PRINT = 0,
    UNEXPECTED_N_ROOTS = 1

};

enum RETURN_CODES_FOR_PRINT PrintSolution (struct Equation eq);

#endif // PRINT_SOLUTION_H_INCLUDED
